# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CS262
email: hellerstein@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  CS262 Graduate database course Berkeley
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jhellerstein.github.io/cs262-06/" # the base hostname & protocol for your site
twitter_username: joe_hellerstein
github_username: jhellerstein 

# Build settings
markdown: kramdown
