            <img src="images/arrow.gif" width="5" height="5">&nbsp;<font size="1"><a href="index.php" class="menu2">Home</a></font><br>
            <img src="images/arrow.gif" width="5" height="5">&nbsp;<font size="1"><a href="basics.php" class="menu2">Basic Info</a></font><br>
            <img src="images/arrow.gif" width="5" height="5">&nbsp;<font size="1"><a href="notes.php" class="menu2">Lecture Notes</a></font><br>
            <img src="images/arrow.gif" width="5" height="5">&nbsp;<font size="1"><a href="syllabus.php" class="menu2">Syllabus</a></font><br>
            <img src="images/arrow.gif" width="5" height="5">&nbsp;<font size="1"><a href="projects.php" class="menu2">Project Ideas</a></font><br>
</font><br>
            
