            <img src="images/arrow.gif" width="5" height="5">&nbsp;<font size="1"><a href="index.html" class="menu2">Home</a></font><br>
            <img src="images/arrow.gif" width="5" height="5">&nbsp;<font size="1"><a href="basics.html" class="menu2">Basic Info</a></font><br>
            <img src="images/arrow.gif" width="5" height="5">&nbsp;<font size="1"><a href="notes.html" class="menu2">Lecture Notes</a></font><br>
            <img src="images/arrow.gif" width="5" height="5">&nbsp;<font size="1"><a href="syllabus.html" class="menu2">Syllabus</a></font><br>
            <img src="images/arrow.gif" width="5" height="5">&nbsp;<font size="1"><a href="projects.html" class="menu2">Project Ideas</a></font><br>
</font><br>
            
